version: '3.8'
services:
 database:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: auth
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"

 cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass secret
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local