version: '3.8'
services:

 
 database:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    restart: always
    environment:
      DB_HOST: database
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - mynet

 cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass secret
    volumes: 
      - cache:/data
    networks:
      - mynet

 app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
      - cache
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: secret
      DB_DATABASE: auth
      DB_PORT: 3306
      APP_PORT: 3000
      JWT_SECRET: m447730ae-e103-4fe6-8018
    networks:
      - mynet

volumes:
  cache:
    driver: local

networks:
  mynet:
    driver: bridge
